config/routes.rb
# Need to not fail when uri contains curly braces
# This overrides the DEFAULT_PARSER with the UNRESERVED key, including '{' and '}'
# DEFAULT_PARSER is used everywhere, so its better to override it once
module URI
  remove_const :DEFAULT_PARSER
  unreserved = REGEXP::PATTERN::UNRESERVED
  DEFAULT_PARSER = Parser.new(:UNRESERVED => unreserved + "\{\}\^")
end

Genie::Application.routes.draw do
  #get "home/index"
  match '/' => redirect('/devices')

  match '/login' => 'sessions#new', :via => :get
  match '/login' => 'sessions#create', :via => :post
  match '/logout' => 'sessions#destroy'

  #root :to => 'home#index'
  match 'devices' => 'devices#index'
  match 'devices/:id' => 'devices#show', :via => :get
  match 'devices/:id' => 'devices#update', :via => :post

  match 'faults' => 'faults#index'
  match 'faults/:id/retry' => 'faults#retry', :via => :post
  match 'faults/:id' => 'faults#destroy', :via => :delete

  match 'presets' => 'presets#update', :via => :post
  match 'presets' => 'presets#index'
  match 'presets/new' => 'presets#new', :via => :get
  match 'presets/:id/edit' => 'presets#edit', :via => :get
  match 'presets/:id' => 'presets#destroy', :via => :delete

  match 'objects' => 'objects#update', :via => :post
  match 'objects' => 'objects#index'
  match 'objects/new' => 'objects#new', :via => :get
  match 'objects/:id/edit' => 'objects#edit', :via => :get
  match 'objects/:id' => 'objects#destroy', :via => :delete

  match 'files' => 'files#upload', :via => :post
  match 'files' => 'files#index'
  match 'files/new' => 'files#new', :via => :get
  match 'files/:id' => 'files#destroy', :via => :delete, :constraints => { :id => /[0-9A-Za-z_\-\.\/]+/ }

  match 'api/:path' => 'api#index', :constraints => { :path => /[0-9A-Za-z_\-\.\/]+/ }

end

app/views/layouts/_menu.html.erb
<% if logged_in? %>
<ul class="menu">

  <li class="<%= params[:controller] == 'devices' ? 'active' : ''%>" >
    <%= link_to 'Devices', devices_path %>
  </li>

  <li class="<%= params[:controller] == 'faults' ? 'active' : ''%>" >
    <%= link_to 'Faults', faults_path %>
  </li>

  <li class="<%= params[:controller] == 'presets' ? 'active' : ''%>" >
    <%= link_to 'Presets', presets_path %>
  </li>

  <li class="<%= params[:controller] == 'objects' ? 'active' : ''%>" >
    <%= link_to 'Objects', objects_path %>
  </li>

  <li class="<%= params[:controller] == 'files' ? 'active' : ''%>" >
    <%= link_to 'Files', files_path %>
  </li>

</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= Rails.application.class.parent_name.titleize %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="/assets/favicon.png" />
</head>
<body>
<div id="header">
  <div id="user_menu" style="float: right; margin: 5px;">
    <% if logged_in? %>
      <%= current_user %> | <%= link_to 'Log out', logout_path %>
    <% else %>
      <%= link_to 'Log in', login_path %>
    <% end %>
  </div>
<%= image_tag logo_image, :class => 'logo' %>
<span class="app-name"><%= Rails.application.class.parent_name.titleize %></span>
<% if not logged_in? %>
<div style="margin-left: 25px;margin-bottom: 10px;color: gray; font-size: 22px;">Demo site</div>
<% end %>
<%= render 'layouts/menu' %>
</div>

<div id="content">
<%- flash.each do |k, v| %>
  <div class="flash <%= k %>"><%= v %></div>
<% end %>

<%= yield %>
</div>

<div id="footer">
&copy;<%= Time.now.year %> genieacs.com
</div>
</body>
</html>